/**
 * Typed helpers for reading the build-time demo snapshot.
 *
 * The snapshot is generated by web/scripts/generate-snapshot.py at build
 * time and committed as web/src/data/snapshot.json. It is never hand-written.
 */

import type { Capsule, LedgerEvent, EntropyResult, PendingAction } from "./types";
import snapshot from "@/data/snapshot.json";

type Snapshot = typeof snapshot;

export function getBeforeCapsule(): Capsule {
  return snapshot.before.capsule as unknown as Capsule;
}

export function getAfterCapsule(): Capsule {
  return snapshot.after.capsule as unknown as Capsule;
}

export function getBeforeEntropy(): EntropyResult {
  return snapshot.before.entropy as unknown as EntropyResult;
}

export function getAfterEntropy(): EntropyResult {
  return snapshot.after.entropy as unknown as EntropyResult;
}

export function getBeforeActions(): PendingAction[] {
  return snapshot.before.actions as unknown as PendingAction[];
}

export function getAfterActions(): PendingAction[] {
  return snapshot.after.actions as unknown as PendingAction[];
}

export function getEvents(): LedgerEvent[] {
  return snapshot.before.events as unknown as LedgerEvent[];
}

export function getEvidence(eventId: string): LedgerEvent | null {
  const ev = (snapshot.before.evidence as Record<string, unknown>)[eventId];
  return (ev as LedgerEvent) ?? null;
}

export function getProjects(): { id: string; name: string; root_path: string }[] {
  return snapshot.before.projects as { id: string; name: string; root_path: string }[];
}
